# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      fail-fast: false # don't abort the entire matrix if one element fails
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - goarch: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20.5"

    - name: Build
      shell: bash
      run: |
        mkdir dist
        mkdir -p ${HOME}/.cache/gopath
        mkdir -p ${HOME}/.cache/go-build
        export GOCACHE=${HOME}/.cache/gopath
        export GOPATH=${HOME}/.cache/go-build
        
        go env
        go get  && echo "Install ok ..." &&  go build ${{matrix.buildflags}} -o dist/port-forwarder-tailscale-${{ matrix.os }}

      env:
        GOARCH: ${{ matrix.goarch }}
        GOCACHE: /home/runner/.cache/go-build
        GOPATH:  /home/runner/.cache/gopath

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: port-forwarder-tailscale
        path: dist/*
